<?php
/*======================================================================*\
|| #################################################################### ||
|| # Package - Joomla Template based on YJSimpleGrid Framework          ||
|| # Copyright (C) 2010  Youjoomla.com. All Rights Reserved.            ||
|| # license - PHP files are licensed under  GNU/GPL V2                 ||
|| # license - CSS  - JS - IMAGE files  are Copyrighted material        ||
|| # bound by Proprietary License of Youjoomla.com                      ||
|| # for more information visit http://www.youjoomla.com/license.html   ||
|| # Redistribution and  modification of this software                  ||
|| # is bounded by its licenses                                         ||
|| # websites - http://www.youjoomla.com | http://www.yjsimplegrid.com  ||
|| #################################################################### ||
\*======================================================================*/
defined( '_JEXEC' ) or die( 'Restricted index access' );
/*  
  !!! DO NOT EDIT THIS FILE. IT MIGHT BE CHANGED ON UPDATE
  this file is custom for this template only. if you wish to edit or add 
  own code to the template, use template_name/custom/yjsg_custom_params.php
  
*/
/*

	this variable is for custom link color. you can use it to style any HTML elements
	see instructions here:
	http://www.yjsimplegrid.com/documentation/advanced/elements-styling-based-on-link-color.html

*/
	
$cc_css ="a{color:".$style_color.";}";

/* K2 CSS */
if (JFactory::getApplication()->input->get( 'option' ) == 'com_k2' 
	|| JModuleHelper::getModule( 'k2_content' )
	|| JModuleHelper::getModule( 'k2_tools' )
	|| JModuleHelper::getModule( 'k2_comments' )
	){
		$document->addStyleSheet($yj_site.'/css/customk.css');
}

/*JS IMAGE EFFECT */
$YjsgCustomJS	= array();
$YjsgCustomJS[] = $yj_site.'/src/styles.js';

/*-- TOP MENU VERTICAL OFFSET --*/
$DDverticalTopOffset = 93;// SmoothDropdown

/*OUT DIVS*/
$yjsg1_before = '<div class="yjsg1_out">';
$yjsg1_after  = '</div>';
$yjsg3_before = '<div class="yjsg3_out">';
$yjsg3_after  = '</div>';
$yjsg5_before = '<div class="yjsg5_out">';
$yjsg5_after  = '</div>';

/*LOGO CENTER*/
if (!$yjsg_header_loaded){
	$document->addStyleDeclaration("
	 	#logo{float:none;margin:0 auto;}
	");
}
/* SHADOW SLIDER PARAMS */
$slider_switch   			= $this->params->get("slider_switch");
$assign_slider_itemid   	= $this->params->get("assign_slider_itemid");
$slide_speed	 			= $this->params->get("slide_speed");
$slide_trans	 			= $this->params->get("slide_trans");
$slider_height	 			= $this->params->get("slider_height");
$slider_width	 			= $this->params->get("slider_width");

/* Conditional css */
if($yjsgBrowser->Name == 'firefox' || $yjsgBrowser->Name == 'msie' && $yjsgBrowser->Version == '9.0' || $yjsgBrowser->Name == 'msie' && $yjsgBrowser->Version == '10.0'){
	 $document->addStyleDeclaration("#YjArtoSlider .navigation{position:relative;top:-10px;}");
}
?>